### ISSUE TITLE
Code review request for AOC 2022 Day 3 

### ISSUE THREAD

**Issue by whippingdot** [vss2sn/advent_of_code#2]
I have been using your repo to see solutions to days for AOC when I am stuck. Unfortunately I have no skill at C++ and cannot understand your day 3 part 1 code. I just wanted to ask - can you tell me why this code is showing me a value 2 thirds of the value that I get when I run your day 3 code with my input? My answer is incorrect but my code seems correct (even with the example problem they gave in the website). Am I missing something? Could you please help me?

```cpp
#include "..\aoc.h"

void Day3Part1()
{
  std::vector<std::string> input = read_file("C:\\Users\\sanja\\OneDrive\\Documents\\Coding\\GitHubProjects\\AdventOfCode-Stuffs\\2022\\aoc\\C++\\day-3\\input.txt");
  int answer = 0;
  int lineSize = 0;
  int counter = 1;
  int times = 1;

  bool found = false;

  std::vector<char> half = std::vector<char>();
  std::vector<char> oldHalf = std::vector<char>();

  std::map<char, int> priorities = std::map<char, int>();
  priorities = { {'a', 1}, {'b', 2}, {'c', 3}, {'d', 4}, {'e', 5}, {'f', 6}, {'g', 7}, {'h', 8}, {'i', 9}, {'j', 10}, {'k', 11}, {'l', 12}, {'m', 13}, {'n', 14}, {'o', 15}, {'p', 16}, {'q', 17}, {'r', 18}, {'s', 19}, {'t', 20}, {'u', 21}, {'v', 22}, {'w', 23}, {'x', 24}, {'y', 25}, {'z', 26}, {'A', 27}, {'B', 28}, {'C', 29}, {'D', 30}, {'E', 31}, {'F', 31}, {'G', 33}, {'H', 34}, {'I', 35}, {'J', 36}, {'K', 37}, {'L', 38}, {'M', 39}, {'N', 40}, {'O', 41}, {'P', 42}, {'Q', 43}, {'R', 44}, {'S', 45}, {'T', 46}, {'U', 47}, {'V', 48}, {'W', 49}, {'X', 50}, {'Y', 51}, {'Z', 52} };

  for (std::string l : input)
  {
    lineSize = l.size();
    for (char c : l)
    {
      half.push_back(c);
      if (counter == lineSize / 2)
      {
        oldHalf = half;
        half.clear();
      }
      else if (counter == lineSize)
      {
        for (char h : half)
        {
          for (char o : oldHalf)
          {
            if (h == o)
            {
              //std::cout << "Size: " << lineSize << "\nCounter: " << counter << "\nH and O: " << h << " and " << o << "\nTIMES " << times << std::endl;
              answer += priorities[o];
              //std::cout << "ANSWER " << answer << std::endl;
              found = true;
              times++;
              break;
            }
          }
          if (found)
          {
            break;
          }
        }
      }
      counter++;
    }
    counter = 1;
    half.clear();
    oldHalf.clear();
    found = false;
  }

  std::cout << "The answer is " << answer << std::endl;
}

int main()
{
  Day3Part1();
  return 0;
}
```

**Comment by whippingdot** [comment]
Not the most efficient I know but I am just doing the AOC to see how many days I can finish. It would be nice if you could tell me where I am straying and not how to improve the speed and all. Like that would be helpful too but I mainly want to know where I am going wrong.

**Comment by vss2sn** [comment]
Hi,

When you open an issue in a repository, it generally implies that there is a bug in the code, or you have a question about the same. Please don't open issues when asking for a code review on unrelated code. The correct place for this question is the advent of code subreddit, where you can tag it with the `Help` flair (like [these](https://www.reddit.com/r/adventofcode/search?q=flair_name%3A%22Help%22&restrict_sr=1) posts).

However, in answer to your question, 'F' should have the value of 32, not 31. As the code snippet does not reveal how you are parsing the file, it's not possible to be sure whether this is the only issue. Hope this helps. :)

**Comment by whippingdot** [comment]
Sorry! And that was the only issue I had found it out before you mentioned it thank you
